FROM node

WORKDIR /root

RUN npm init -y
RUN npm install --save-dev webpack webpack-cli
RUN npm install --save-dev babel-cli babel-preset-react babel-loader
RUN npm install --save-dev react react-dom

ADD nginx/webpack.config.js /root/webpack.config.js
ADD nginx/src /root/src
RUN mkdir dist

RUN npx webpack

FROM nginx:1.15

ADD nginx/entrypoint.sh /root/entrypoint.sh
ADD nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /root/dist /usr/share/nginx/html/assets
ADD nginx/index.html /usr/share/nginx/html/index.html

ENTRYPOINT ["/root/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
