---
version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
      JENKINS_OPTS: "--prefix=/jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins-home:/var/jenkins_home"
  nginx:
    image: nginx:1.15
    entrypoint: ["/root/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "443:443"
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/ssl:/etc/nginx/ssl"
      - "./nginx/entrypoint.sh:/root/entrypoint.sh"
volumes:
  jenkins-home: {}
