---
version: "3"
services:
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   restart: always
  #   entrypoint: ["/usr/local/bin/entrypoint.sh"]
  #   command: ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
  #   environment:
  #     JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
  #     JENKINS_OPTS: "--prefix=/jenkins"
  #   ports:
  #     - "50000:50000"
  #   volumes:
  #     - "jenkins-home:/var/jenkins_home"
  #     - "./jenkins/entrypoint.sh:/usr/local/bin/entrypoint.sh"
  # nginx:
  #   image: nginx:1.15
  #   restart: always
  #   entrypoint: ["/root/entrypoint.sh"]
  #   command: ["nginx", "-g", "daemon off;"]
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
  #     - "./nginx/ssl:/etc/nginx/ssl"
  #     - "./nginx/entrypoint.sh:/root/entrypoint.sh"
  zookeeper:
    image: zookeeper:3.4
    restart: always
    environment:
      JVMFLAGS: "-Xms64m -Xmx128m"
  kafka:
    image: wurstmeister/kafka:1.1.0
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
      KAFKA_BROKER_ID: "1"
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
volumes:
  jenkins-home: {}
