FROM node

RUN mkdir /usr/local/web
WORKDIR /usr/local/web

ENV NODE_ENV production

ADD web/package*.json ./
RUN npm install
ADD web .

RUN npx webpack

FROM nginx:1.15

ADD nginx/entrypoint.sh /root/entrypoint.sh
ADD nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /usr/local/web/dist/index.html /usr/share/nginx/html/index.html
COPY --from=0 /usr/local/web/dist/assets /usr/share/nginx/html/assets

ENTRYPOINT ["/root/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
