FROM golang

RUN apt-get update
RUN apt-get install unzip

RUN wget https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip -O /usr/local/protoc-3.6.0-linux-x86_64.zip
RUN mkdir /usr/local/protoc
RUN unzip /usr/local/protoc-3.6.0-linux-x86_64.zip -d /usr/local/protoc
RUN rm /usr/local/protoc-3.6.0-linux-x86_64.zip
ENV PATH /usr/local/protoc/bin:$PATH

RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN go get -u google.golang.org/api/gmail/v1
RUN go get -u golang.org/x/oauth2/...
RUN go get -u github.com/robfig/cron
RUN go get -u github.com/Shopify/sarama
RUN go get -u github.com/golang/protobuf/proto

ADD common /go/src/github.com/katsuya94/shizuku/common
WORKDIR /go/src/github.com/katsuya94/shizuku/common
RUN protoc --go_out=. *.proto

ADD mailstream /go/src/github.com/katsuya94/shizuku/mailstream
RUN go install github.com/katsuya94/shizuku/mailstream

FROM debian:stretch

RUN apt-get update
RUN apt-get install -y ca-certificates
COPY --from=0 /go/bin/mailstream /root/mailstream
WORKDIR /root
ENTRYPOINT ["./mailstream"]
