---
version: "3"
services:
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   restart: always
  #   entrypoint: ["/usr/local/bin/entrypoint.sh"]
  #   command: ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
  #   environment:
  #     JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
  #     JENKINS_OPTS: "--prefix=/jenkins"
  #   ports:
  #     - "50000:50000"
  #   volumes:
  #     - "jenkins-home:/var/jenkins_home"
  #     - "./jenkins/entrypoint.sh:/usr/local/bin/entrypoint.sh"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/ssl:/etc/nginx/ssl"
  zookeeper:
    image: zookeeper:3.4
    restart: always
    environment:
      JVMFLAGS: "-Xms64m -Xmx128m"
  kafka:
    image: wurstmeister/kafka:1.1.0
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
      KAFKA_BROKER_ID: "1"
      KAFKA_HEAP_OPTS: "-Xms128m -Xmx256m"
  mailstream:
    build:
      context: .
      dockerfile: Dockerfile-mailstream
    restart: always
    volumes:
      - "./mailstream/config:/root/config"
volumes:
  jenkins-home: {}
